import Head from "next/head";
import Link from "next/link";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/muhammad.jpeg";
import code from "../public/web-development.png";
import design from "../public/web-frontend.png";
import cloud from "../public/cloud-computing.png";
import Image from "next/image";
import web1 from "../public/construction.png";
import web2 from "../public/pepiq.png";
import web3 from "../public/dashboard.png";
import web4 from "../public/house.png";
import web5 from "../public/s-seeker.png";
import web6 from "../public/qauzza.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Muhammad Alabadsa</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://docs.google.com/document/d/1WIESR_ugZzjDCkidSlJVQoRbbzDfGk40Y1VEniU6aQQ/edit?usp=sharing"
                  download
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Muhammad Alabadsa
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Full-Stack Developer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Freelancer providing services for programming and design content
              needs. Join me down below and let&apos;s get cracking!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <Link href="https://twitter.com/MOH22389">
                <AiFillTwitterCircle style={{ cursor: "pointer" }} />
              </Link>
              <Link href="https://www.linkedin.com/in/muhammad-al-abadsa-95b28a175/">
                <AiFillLinkedin style={{ cursor: "pointer" }} />
              </Link>
              <Link href="https://github.com/mAbadsa">
                <AiFillGithub style={{ cursor: "pointer" }} />
              </Link>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" alt="avatar" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance developer,
              I&apos;ve done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including static website,
              full-stack apps, and AWS services.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} alt="design" />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant website suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">
                Development Framework I Use
              </h4>
              <p className="text-gray-800 py-1">ReactJs</p>
              <p className="text-gray-800 py-1">NextJs</p>
              <p className="text-gray-800 py-1">Material-UI</p>
              <p className="text-gray-800 py-1">Ant-design</p>
              <p className="text-gray-800 py-1">Tailwind CSS</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} alt="code" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let&apos;s make
                it a reality.
              </p>
              <h4 className="py-4 text-teal-600">
                Programming Languages I Use
              </h4>
              <p className="text-gray-800 py-1">NodeJs</p>
              <p className="text-gray-800 py-1">Typescript</p>
              <p className="text-gray-800 py-1">Expressjs</p>
              <p className="text-gray-800 py-1">NestJs</p>
              <p className="text-gray-800 py-1">PostgreSQL</p>
              <p className="text-gray-800 py-1">MongoDB</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={cloud} width={100} height={100} alt="cloud" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">AWS Services</h3>
              <p className="py-2">
                Do you want to deploy your app on AWS securly? Let&apos;s make
                it a reality..
              </p>
              <h4 className="py-4 text-teal-600">AWS services</h4>
              <p className="text-gray-800 py-1">Solution Architect</p>
              <p className="text-gray-800 py-1">Deployment</p>
              <p className="text-gray-800 py-1">S3</p>
              <p className="text-gray-800 py-1">Codepipline</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance developer,
              I&apos;ve done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including static website,
              full-stack apps, and AWS services.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
                style={{ objectFit: "contain" }}
                alt="web1"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                style={{ objectFit: "contain" }}
                src={web2}
                alt="web2"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                style={{ objectFit: "contain" }}
                src={web3}
                alt="web3"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
                style={{ objectFit: "contain" }}
                alt="web4"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
                style={{ objectFit: "contain" }}
                alt="web4"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
                style={{ objectFit: "contain" }}
                alt="web4"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}

